##
## author: Michal Tomczuk <michal.tomczuk@zerodowntime.pl>
##

---
- name: install apache2
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - libapache2-mod-wsgi
  when:
    ansible_distribution == 'Ubuntu'
