##
## author: Michal Tomczuk <michal.tomczuk@zerodowntime.pl>
##

---
- name: add grafana repo key
  apt_key: url=https://packagecloud.io/gpg.key state=present
  when:
    ansible_distribution == 'Ubuntu'

- name: add grafana repo to apt
  apt_repository:
    repo='deb https://packagecloud.io/grafana/stable/debian/ wheezy main'
    state=present
  when:
    ansible_distribution == 'Ubuntu'

- name: install graphite
  apt: name=grafana state=present
  when:
    ansible_distribution == 'Ubuntu'
